; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.39/platform-espressif32.zip
framework = arduino
board = esp32dev
board_build.partitions = min_spiffs.csv
extra_scripts = extra_script.py
monitor_speed = 115200  ; Sets the Serial Monitor baud rate
upload_speed = 921600   ; Optional: Speeds up flashing code to the board
;build_flags = -D CORE_DEBUG_LEVEL=5  ; Optional: Enables detailed debug output for troubleshooting
; 1: Errors only2: Errors and warnings3: Errors, warnings, and info4: Errors, warnings, info, and debug5: Verbose (includes all logging)

[env:denky32]
platform = espressif32
board = denky32
framework = arduino
